backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "notices"
    label: "নোটিশ"
    folder: "content/notices"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "নোটিশ", name: "body", widget: "markdown" }
  - name: "teachers"
    label: "শিক্ষকবৃন্দ"
    folder: "content/teachers"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "নাম", name: "name", widget: "string" }
      - { label: "পদবি", name: "designation", widget: "string" }
      - { label: "বিষয়", name: "subject", widget: "string" }
      - { label: "ছবি", name: "photo", widget: "image" }
      - { label: "জীবনবৃত্তান্ত", name: "body", widget: "markdown" }
